/*
 * nRF9151 GPS tracker — active mode
 *
 * loc_fsm decides who gets the shared radio (GNSS vs LTE) and what to publish;
 * this file executes that policy: modem bring-up and the publish loop. Reports
 * go as protobuf (proto/tracker.proto, encoders generated by nanopb) in
 * non-confirmable CoAP POSTs over UDP — fire-and-forget like the old MQTT
 * QoS 0, but ~4x cheaper on air and with no TCP ACK tail holding RRC open.
 * LTE registers once at boot and stays registered — PSM parks the radio between
 * sends, which is what gives GNSS its acquisition windows.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <math.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <nrf_modem_gnss.h>
#include <modem/nrf_modem_lib.h>
#include <hw_id.h>

#include "loc_fsm.h"
#include "motion.h"
#include "imu.h"
#include "agnss.h"
#include "cell_info.h"
#include "gnss_ctrl.h"
#include "lte_ctrl.h"
#include "coap_pub.h"
#include "obs_queue.h"
#include "event_queue.h"
#include "uplink.h"
#include "log_uplink.h"
#include "leds.h"
#include "guard.h"
#ifdef CONFIG_TRACKER_FLOG
#include "flog.h"
#endif

LOG_MODULE_REGISTER(tracker, CONFIG_TRACKER_LOG_LEVEL);

/* ── configuration ──────────────────────────────────────────────── */
#define SERVER_HOST       CONFIG_TRACKER_SERVER_HOST
#define SERVER_PORT       CONFIG_TRACKER_SERVER_PORT

#define POST_INTERVAL_MS  (CONFIG_TRACKER_POST_INTERVAL_S * 1000)
#define STATUS_INTERVAL_MS 5000
/* GPS staleness now lives in loc_fsm, which owns the fix bookkeeping. */
#define NET_RETRY_MS      10000  /* between socket-setup attempts */
/* Flush cadence and all other send policy live in uplink now. */

/* ── state ───────────────────────────────────────────────────────── */
static char device_id[HW_ID_LEN];

/* ── status block ─────────────────────────────────────────────────  */
static void print_status(const struct nrf_modem_gnss_pvt_data_frame *p,
			 const struct loc_status *loc,
			 const struct ephe_inventory *inv, int64_t uptime_ms,
			 bool gnss_live)
{
	LOG_DBG("===== status @ %llds =====", (long long)(uptime_ms / 1000));

	/* LTE status: registration state + serving-cell details (same cached
	 * AT%XMONITOR read used for the cell-location fallback). */
	struct serving_cell sc;

	if (cell_info_read(&sc) == 0 && sc.valid) {
		LOG_DBG("LTE:  %s | op %s | band %d | cell %u | RSRP %d dBm",
			lte_ctrl_status_str(), sc.op, sc.band, sc.cid,
			sc.rsrp_dbm);
	} else {
		LOG_DBG("LTE:  %s", lte_ctrl_status_str());
	}

	/* GNSS status. With the receiver stopped, the pvt buffer is a frozen
	 * frame — narrating it as "searching" misled a live debug session. */
	if (!gnss_live) {
		LOG_DBG("GNSS: off");
	} else if (p->flags & NRF_MODEM_GNSS_PVT_FLAG_FIX_VALID) {
		LOG_DBG("GNSS: FIX  %.6f, %.6f  alt %.1fm  acc %.1fm  sats %u/%u",
			p->latitude, p->longitude,
			(double)p->altitude, (double)p->accuracy,
			loc->used, loc->tracked);
	} else {
		LOG_DBG("GNSS: searching  flags 0x%02x", p->flags);
		/* These two mean different things and want different fixes:
		 *   DEADLINE_MISSED        no window at all since the last PVT — LTE
		 *                          is transmitting; only backing off LTE helps.
		 *   NOT_ENOUGH_WINDOW_TIME windows exist but are too short — the case
		 *                          nrf_modem_gnss_prio_mode_enable() is for.
		 *
		 * Both are CONDITIONS, not events: they persist for minutes during
		 * LTE/GNSS contention, and per-pass WRNs would flood the uplink
		 * (dozens of lines per episode). Log the edges — onset at WRN,
		 * clear at INF — and leave the per-pass view to the DBG flags line
		 * above. Same pattern as the gnss_blocked edge. */
		static bool no_window_prev, short_window_prev;
		bool no_window = p->flags & NRF_MODEM_GNSS_PVT_FLAG_DEADLINE_MISSED;
		bool short_window =
			p->flags & NRF_MODEM_GNSS_PVT_FLAG_NOT_ENOUGH_WINDOW_TIME;

		/* These edges diagnose LTE/GNSS contention during CONTINUOUS
		 * tracking. In periodic mode every uplink flush trivially chops
		 * the sleeping receiver — the overnight parked log was 137 WRNs
		 * of exactly that. Meaningless there; don't evaluate. */
		if (loc->gnss_mode != LOC_GNSS_CONTINUOUS) {
			no_window_prev = no_window;
			short_window_prev = short_window;
		} else {
			if (no_window != no_window_prev) {
				no_window_prev = no_window;
				if (no_window) {
					LOG_WRN("GNSS: no window since last PVT (LTE active)");
				} else {
					LOG_INF("GNSS: windows back");
				}
			}
			if (short_window != short_window_prev) {
				short_window_prev = short_window;
				if (short_window) {
					LOG_WRN("GNSS: windows too short (no PSM/eDRX?)");
				} else {
					LOG_INF("GNSS: window length ok");
				}
			}
		}
	}
	loc_fsm_log(loc, p, inv);

	int psm_tau_s, psm_active_s;

	lte_ctrl_psm(&psm_tau_s, &psm_active_s);
	if (psm_active_s < 0) {
		LOG_DBG("LTE:  RRC %s | PSM not granted",
			lte_ctrl_rrc_connected() ? "connected" : "idle");
	} else {
		LOG_DBG("LTE:  RRC %s | PSM TAU %ds active %ds",
			lte_ctrl_rrc_connected() ? "connected" : "idle",
			psm_tau_s, psm_active_s);
	}

	/* PDN state next to socket state, so a "no socket" that is really
	 * "PDN not up yet" is obvious in the log. */
	LOG_DBG("net:  %s | pdn %s", coap_pub_ready() ? "ready" : "no socket",
		lte_ctrl_pdn_active() ? "active" : "down");
}

/* Send-health policy (the uplink liveness watchdog): the offloaded send is
 * bounded by SO_SNDTIMEO, so a wedged modem surfaces as timeout errors from
 * uplink_poll instead of a frozen loop. Episode shape, agreed 2026-07-23:
 * first timeout = one WRN + a modem post-mortem (%CONEVAL/+CEER/+CEREG into
 * flash — may itself hang, which the watchdog turns into its own evidence);
 * a second consecutive timeout = the modem answers nothing a reset would
 * not fix faster — guard reboot with a named note. A success in between
 * closes the episode at INF. Only timeout errnos escalate: encode bugs and
 * socket races are not modem death. */
static uint8_t send_fail_streak;

/* A datagram left the device: pulse the TX LED, stamp the RRC-tail
 * measurement, and tell the FSM when the coarse position is on the map (it
 * holds the radio for GNSS until the boot cell report is out). */
static void on_uplink_sent(uint32_t kinds_mask)
{
	leds_tx_pulse();
	lte_ctrl_note_publish(k_uptime_get());
	if (kinds_mask & UPLINK_KIND_CELL) {
		loc_fsm_note_cell_sent();
	}
	if (send_fail_streak) {
		send_fail_streak = 0;
		LOG_INF("uplink sends recovered");
	}
}

/* ── main ─────────────────────────────────────────────────────────  */
int main(void)
{
	int err;

	/* Flight recorder first: the boot lines below are exactly the ones a
	 * post-mortem wants. Failure leaves it offline, never blocks boot. */
#ifdef CONFIG_TRACKER_FLOG
	(void)flog_init();
#endif

	LOG_INF("tracker starting");
	/* Right after the boot identity: if the last session died (watchdog,
	 * modem fault), its death certificate is the next line out. */
	guard_init();

	err = nrf_modem_lib_init();
	if (err) {
		LOG_ERR("modem init: %d", err);
		return err;
	}

	/* Device identity: IMEI on hardware, env/Kconfig on native_sim */
	err = hw_id_get(device_id, sizeof(device_id));
	if (err) {
		LOG_ERR("hw_id_get: %d", err);
		return err;
	}
	LOG_INF("device id: %s", device_id);
	LOG_INF("server: coap://%s:%d/obs", SERVER_HOST, SERVER_PORT);
	/* Uplink owns the envelope + flush policy; obs store and the log ring
	 * register as its sources. GPS samples land at the publish interval —
	 * a track segment's time model (anchor + i*dt) is built on it. */
	uplink_init(device_id);
	uplink_on_sent(on_uplink_sent);
	obs_queue_init(POST_INTERVAL_MS);
	event_queue_init();
	log_uplink_init();
	agnss_set_device_id(device_id);
	leds_init();

	/* Start LTE async — don't block, status loop shows progress */
	LOG_INF("starting LTE (async)...");
	err = lte_ctrl_start();
	if (err) {
		return err;
	}

	/* Configure GNSS but do NOT start it yet. An unregistered modem runs a
	 * continuous cell search; GNSS running against that starves the search and
	 * gains nothing itself. loc_fsm starts it once LTE has registered. */
	err = gnss_ctrl_configure();
	if (err) {
		LOG_ERR("gnss configure: %d", err);
		return err;
	}
	bool gnss_blocked_prev = false;
	/* Snapshot of the most recent PVT frame with FIX_VALID set. The live `pvt`
	 * global only carries defined lat/lon while the flag is set, but the FSM
	 * lets us publish for up to GPS_STALE_S after the fix lapses -- those
	 * publishes must come from this copy, not from whatever an unfixed frame
	 * happens to contain. (static: ~700 B, keep off the main stack) */
	static struct nrf_modem_gnss_pvt_data_frame fix_pvt;
	int64_t fix_pvt_ms = 0; /* when fix_pvt was captured, for the age field */

	/* Wake-PVT forensics (phantom investigation, 2026-07-12): the
	 * receiver marks the first PVT after a duty-cycle sleep
	 * (SLEEP_BETWEEN_PVT) and frames from its self-scheduled ephemeris
	 * downloads (SCHED_DOWNLOAD) — exactly the epochs implicated in the
	 * 501 m time-true/position-stale point. Hold the newest one and log
	 * it when the FSM leaves a parked state, so departure points arrive
	 * pre-labeled: one INF line per departure, never per wake (a parked
	 * night has ~720 wakes; the wire budget says no). */
	static struct {
		int64_t ms;
		bool slept;
		bool sched;
		bool fix;
		float acc;
	} last_wake;
	uint32_t wake_pvts = 0, wake_fixes = 0, sched_pvts = 0;

	int64_t last_post_ms   = 0;
	int64_t queued_fix_ms  = 0;
	int64_t last_acq_log_ms = 0;
	int64_t last_status_ms = 0;
	int64_t next_net_ms    = 0;
	enum loc_state prev_state = LOC_LTE_ATTACH;
	struct loc_status loc = { .state = LOC_LTE_ATTACH };

	loc_fsm_init(k_uptime_get());
	motion_init(k_uptime_get());
	/* Boot picks the parked mode: IMU present = GNSS off while parked,
	 * accelerometer owns departure; absent = legacy periodic checks.
	 * Trusted absolutely after this probe — no runtime health checks.
	 * The LED pulse is wired here (before triggers can fire) so imu never
	 * depends on ui. */
	imu_on_motion(leds_imu_pulse);
	loc_fsm_set_imu_wake(imu_init());
	LOG_INF("IMU: %s", imu_present() ?
		"present — quiescent wake source is the accelerometer" :
		"absent — quiescent wake source is GPS checks");

	for (;;) {
		/* One feed per pass: any pass that stalls past
		 * TRACKER_GUARD_WDT_S (a blocking modem call that never
		 * returns — both field freezes) reboots into a clean session
		 * with a named death note instead of a silent coma. */
		guard_feed();

		/* Wait for next PVT event (1 Hz) with a 2s timeout so the
		 * status block still prints even if GNSS is blocked by LTE. */
		gnss_ctrl_wait_pvt(K_SECONDS(2));

		const struct nrf_modem_gnss_pvt_data_frame *pvt = gnss_ctrl_pvt();
		int64_t now = k_uptime_get();

		/* One inventory digest per pass; loc_fsm and agnss read the
		 * same snapshot (the C2 gate and the fetch trigger must agree). */
		gnss_ctrl_poll_inventory(now);

		const struct ephe_inventory *inv = gnss_ctrl_inventory();

		/* With GNSS stopped (PARKED in IMU mode, LTE_ATTACH) the pvt
		 * buffer is a FROZEN copy of the last frame — often FIX_VALID
		 * from the parking fix. Re-processing it every 2 s tick would
		 * ghost-refresh staleness, motion evidence and wake forensics
		 * forever; treat it as no observation at all. */
		bool gnss_live = (gnss_ctrl_mode() != LOC_GNSS_OFF);

		if (gnss_live &&
		    (pvt->flags & (NRF_MODEM_GNSS_PVT_FLAG_SLEEP_BETWEEN_PVT |
				   NRF_MODEM_GNSS_PVT_FLAG_SCHED_DOWNLOAD))) {
			last_wake.ms    = now;
			last_wake.slept = pvt->flags &
				NRF_MODEM_GNSS_PVT_FLAG_SLEEP_BETWEEN_PVT;
			last_wake.sched = pvt->flags &
				NRF_MODEM_GNSS_PVT_FLAG_SCHED_DOWNLOAD;
			last_wake.fix   = pvt->flags &
				NRF_MODEM_GNSS_PVT_FLAG_FIX_VALID;
			last_wake.acc   = pvt->accuracy;
			wake_pvts++;
			wake_fixes += last_wake.fix;
			sched_pvts += last_wake.sched;
		}

		static const struct nrf_modem_gnss_pvt_data_frame quiet = {
			.flags = NRF_MODEM_GNSS_PVT_FLAG_DEADLINE_MISSED,
		};

		if (gnss_live &&
		    (pvt->flags & NRF_MODEM_GNSS_PVT_FLAG_FIX_VALID)) {
			/* Known cosmetic quirk, deliberately NOT special-cased:
			 * the first fix after a periodic-mode sleep can carry a
			 * near-pre-sleep position (solver seeded with held state;
			 * field-observed once, 501 m off, corrected next epoch;
			 * DevZone-corroborated class). Pipeline audit 2026-07-12
			 * proved timestamps are capture-time end-to-end, so such
			 * a point is time-true/position-stale. One odd map point
			 * per rare wake beats permanently shipped validation
			 * logic that may never fire again — detect in the DB via
			 * impossible implied speed if it ever matters. */
			fix_pvt = *pvt;
			fix_pvt_ms = now;
			motion_note_gps(pvt->latitude, pvt->longitude,
					(double)pvt->accuracy, now);
		}

		/* IMU any-motion interrupt. While quiescent it is the WAKE:
		 * raise an alert event (jumps the uplink queue, so the server
		 * learns "your asset moved" within seconds) and break the
		 * stationary verdict so the FSM leaves for REPORT_CELL.
		 * While already moving it is noise the verdict reflects. */
		if (imu_take_motion()) {
			if (loc.state == LOC_QUIESCENT) {
				event_queue_add(EVENT_REASON_IMU_WAKE, now);
			}
			motion_note_imu(now);
		}

		/* Policy first: it owns the fix-staleness and ephemeris bookkeeping.
		 * The supply verdict gates the C2 escalation (see loc_fsm.h). */
		loc_fsm_set_agnss_supply(agnss_supply_ok());
		loc_fsm_update(gnss_live ? pvt : &quiet, inv, now,
			       lte_ctrl_registered(), motion_stationary(now),
			       &loc);
		leds_update(&loc, lte_ctrl_registered());

		/* First parked entry of this boot: checkpoint the modem's NVM
		 * (see lte_ctrl.c). CFUN=0 takes everything down — socket,
		 * registration, GNSS — so close the socket and force the GNSS
		 * mode to be reapplied; the FSM sees the registration drop and
		 * walks the normal re-attach path. */
		if (loc.state == LOC_QUIESCENT && lte_ctrl_checkpoint_due()) {
			coap_pub_close();
			lte_ctrl_checkpoint();
			gnss_ctrl_mark_off();
		}

		/* Apply the FSM's GNSS mode. Runs GNSS only when the FSM says
		 * so (a searching modem owns the radio), and switches between
		 * continuous 1 Hz and the modem's periodic-navigation mode
		 * when the parked states ask for it. */
		gnss_ctrl_apply(loc.gnss_mode, loc.gnss_interval_s);

		/* GNSS_EXCLUSIVE: take the LTE stack down entirely so idle-mode
		 * DRX/reselection can't slice GNSS; bring it back on exit. GNSS
		 * keeps running across both edges — DEACTIVATE_LTE leaves it be. */
		if (!loc.lte_wanted && lte_ctrl_stack_on()) {
			LOG_WRN("deactivating LTE — GNSS gets the radio outright");
			(void)lte_ctrl_set_stack(false);
			coap_pub_close(); /* socket dies with the PDN */
		} else if (loc.lte_wanted && !lte_ctrl_stack_on()) {
			LOG_INF("re-activating LTE (re-attach follows)");
			(void)lte_ctrl_set_stack(true);
		}

		/* A PDN drop (deactivation or network-side) orphans the UDP socket;
		 * recreate it when the PDN returns rather than sending into a void. */
		if (!lte_ctrl_pdn_active() && coap_pub_ready()) {
			LOG_WRN("PDN down — closing CoAP socket");
			coap_pub_close();
		}

		/* Deferred LTE work (the CEER post-mortem after a loss). */
		lte_ctrl_poll();

		/* EVT_BLOCKED/UNBLOCKED arrive in ISR context; log the edge here. */
		if (gnss_ctrl_blocked() != gnss_blocked_prev) {
			gnss_blocked_prev = !gnss_blocked_prev;
			LOG_DBG("GNSS: %s by LTE",
				gnss_blocked_prev ? "blocked" : "unblocked");
		}

		/* One-time UDP socket setup, retried on failure. Needs LTE up (DNS
		 * goes over the PDN) and is gated on publish_allowed so even the
		 * getaddrinfo exchange stays out of GNSS quiet windows. There is no
		 * connection to keep alive: UDP is silent between sends by nature,
		 * which is the whole point of the CoAP move. Gated on pdn_active
		 * too: before the default PDN has an IP, getaddrinfo/socket can
		 * only fail. (Always true on native_sim.) */
		if (loc.publish_allowed && lte_ctrl_pdn_active() &&
		    lte_ctrl_registered() && !coap_pub_ready() &&
		    now >= next_net_ms) {
			next_net_ms = now + NET_RETRY_MS;
			if (coap_pub_init(SERVER_HOST, SERVER_PORT)) {
				LOG_WRN("CoAP setup failed (retry in %d s)",
					NET_RETRY_MS / 1000);
			}
		}

		/* Acquisition forensics: while hunting (or waiting on a stale
		 * fix), ship one compact sky snapshot at INF every 30 s so a
		 * drive-time acquisition failure is diagnosable from the server
		 * — the per-satellite DBG table never leaves UART. Bounded:
		 * ~70 B/line only while unfixed, so a 5-min episode is ~700 B.
		 * ephe V/H: V of the H satellites we hold ephemeris for are
		 * currently visible; a fix needs 4 visible. */
		bool hunting = (loc.state == LOC_GNSS_ACQUIRE ||
				loc.state == LOC_GNSS_EXCLUSIVE ||
				(loc.state == LOC_REPORT_GNSS && !loc.gps_current));
		if (hunting && now - last_acq_log_ms >= 30000) {
			last_acq_log_ms = now;
			LOG_INF("acq: %s tracked %u strong %u ephe %u/%u empty %u pdop %.1f",
				loc_state_str(loc.state), loc.tracked, loc.strong,
				loc.ephemeris_visible, loc.ephemeris_held,
				loc.sky_empty, (double)loc.pdop);
		}

		/* Status block every STATUS_INTERVAL_MS */
		/* While quiescent nothing changes second to second; a calm
		 * device should read calm on the console too. */
		int64_t status_ivl = (loc.state == LOC_QUIESCENT)
			? 60000 : STATUS_INTERVAL_MS;
		if (now - last_status_ms >= status_ivl) {
			last_status_ms = now;
			print_status(pvt, &loc, inv, now, gnss_live);
			if (wake_pvts) {
				/* UART-only prevalence stats (DBG never
				 * ships): do ALL wakes carry the flag? */
				LOG_DBG("wake: %u pvts %u fixes %u sched-dl",
					wake_pvts, wake_fixes, sched_pvts);
			}
		}

		/* SAMPLE at the FSM's cadence — free, no radio involved. GPS
		 * samples come from the fix-valid snapshot; within ~10 m of the
		 * previous point they queue as 4 B repeat entries. */
		if (loc.publish_allowed && now - last_post_ms >= loc.publish_interval_ms) {
			last_post_ms = now;
			if (!loc.prefer_cell) {
				/* Only if the snapshot is NEW: while LTE holds the
				 * radio GNSS produces no PVT, and re-queueing the
				 * same snapshot each interval shipped identical
				 * points 10x (seen in the server DB). */
				if (fix_pvt_ms != queued_fix_ms) {
					queued_fix_ms = fix_pvt_ms;
					obs_queue_add_gps(&fix_pvt, fix_pvt_ms);
				}
			} else if (lte_ctrl_registered()) {
				struct serving_cell sc;
				/* Condition, not event: don't repeat the WRN every
				 * cell interval while XMONITOR keeps failing. */
				static bool cell_unavail;

				if (cell_info_read(&sc) == 0 && sc.valid) {
					cell_unavail = false;
					obs_queue_add_cell(sc.mcc, sc.mnc, sc.tac,
							   sc.cid, sc.rsrp_dbm,
							   sc.act, now);
					motion_note_cell(sc.cid, now);
				} else if (!cell_unavail) {
					cell_unavail = true;
					LOG_WRN("serving cell unavailable");
				}
			}
		}

		/* SHIP: uplink owns all flush policy (timer / fullness / urgent).
		 * We hand it the radio verdict and tick it; a state change is
		 * the one policy input only this loop can see (a fresh fix or
		 * boot cell report should reach the map now, not in 2 min). */
		if (loc.state != prev_state) {
			/* Departure forensics: label what the wake's PVT
			 * claimed, once, before prev_state is overwritten. */
			if (prev_state == LOC_QUIESCENT && last_wake.ms != 0) {
				LOG_INF("GNSS: wake PVT %ds ago: sleep=%d "
					"sched-dl=%d fix=%d acc=%d",
					(int)((now - last_wake.ms) / 1000),
					last_wake.slept, last_wake.sched,
					last_wake.fix, (int)last_wake.acc);
				last_wake.ms = 0; /* log each wake once */
			}
			prev_state = loc.state;
			uplink_request_flush(UPLINK_FLUSH_URGENT);
		}
		/* Parked = slow flush timer. Keyed on the FSM state (not the
		 * raw verdict) so shipping only slows once actually quiesced;
		 * the QUIESCENT->REPORT_GNSS transition urgent-flushes above,
		 * so motion still reaches the map in seconds. */
		uplink_set_flush_interval(loc.state == LOC_QUIESCENT
			? (uint32_t)CONFIG_TRACKER_QUIESCENT_FLUSH_S * 1000
			: (uint32_t)CONFIG_TRACKER_FLUSH_INTERVAL_S * 1000);
		uplink_set_allowed(loc.publish_allowed);

		int uerr = uplink_poll(now);

		if (uerr == -EAGAIN || uerr == -ETIMEDOUT) {
			send_fail_streak++;
			if (send_fail_streak == 1) {
				LOG_WRN("uplink send timed out — modem "
					"unresponsive? (retry next flush)");
				lte_ctrl_post_mortem();
			} else {
				guard_modem_dead(); /* no return on hardware */
			}
		}

		/* A-GNSS: opportunistic assistance fetch while the radio is
		 * already ours (the FSM's agnss_fetch_allowed verdict; fetch
		 * execution and pacing live in agnss.c). */
		agnss_poll(now, &loc, inv);
	}

	return 0;
}
