/*
 * nRF9151 GPS tracker — active mode
 *
 * loc_fsm decides who gets the shared radio (GNSS vs LTE) and what to publish;
 * this file executes that policy: modem bring-up and the publish loop. Reports
 * go as protobuf (proto/tracker.proto, encoders generated by nanopb) in
 * non-confirmable CoAP POSTs over UDP — fire-and-forget like the old MQTT
 * QoS 0, but ~4x cheaper on air and with no TCP ACK tail holding RRC open.
 * LTE registers once at boot and stays registered — PSM parks the radio between
 * sends, which is what gives GNSS its acquisition windows.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <math.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <nrf_modem_gnss.h>
#include <nrf_modem_at.h>
#include <modem/nrf_modem_lib.h>
#include <modem/lte_lc.h>
#include <hw_id.h>

#include "loc_fsm.h"
#include "coap_pub.h"
#include "obs_queue.h"

LOG_MODULE_REGISTER(tracker, CONFIG_TRACKER_LOG_LEVEL);

/* ── configuration ──────────────────────────────────────────────── */
#define SERVER_HOST       CONFIG_TRACKER_SERVER_HOST
#define SERVER_PORT       CONFIG_TRACKER_SERVER_PORT

#define GNSS_INTERVAL_S   1   /* PVT event rate */
#define POST_INTERVAL_MS  (CONFIG_TRACKER_POST_INTERVAL_S * 1000)
#define STATUS_INTERVAL_MS 5000
/* GPS staleness now lives in loc_fsm, which owns the fix bookkeeping. */
#define NET_RETRY_MS      10000  /* between socket-setup attempts */
/* Queue flush cadence: one datagram per interval amortizes the ~47 B
 * CoAP/UDP/IP overhead across ~12 samples. State changes flush immediately. */
#define FLUSH_INTERVAL_MS (CONFIG_TRACKER_FLUSH_INTERVAL_S * 1000)

/* RSRP index → dBm (same formula as modem_info.h RSRP_IDX_TO_DBM). */
#define RSRP_IDX_TO_DBM(idx) ((idx) < 0 ? (idx) - 140 : (idx) - 141)

/* Serving-cell identity, parsed from AT%XMONITOR (cached registration data —
 * no radio scan). Enough for an OpenCelliD single-cell lookup. */
struct serving_cell {
	int      mcc;
	int      mnc;
	uint32_t tac;
	uint32_t cid;
	int      rsrp_dbm;
	int      band;
	char     op[32];
	bool     valid;
};

/* ── state ───────────────────────────────────────────────────────── */
static struct nrf_modem_gnss_pvt_data_frame pvt;
static K_SEM_DEFINE(pvt_sem, 0, 1);

static enum lte_lc_nw_reg_status lte_status = LTE_LC_NW_REG_NOT_REGISTERED;
/* Set from the LTE callback thread, polled by the main loop. */
static volatile bool lte_connected;

/* Registration (lte_connected) is NOT the same as having an active default
 * PDN with an assigned IP; sockets and DNS only work once the PDN is up, so
 * socket setup gates on this. On native_sim CONFIG_LTE_LC_PDN_MODULE is off
 * (host sockets are always up), so default to true there. */
#if defined(CONFIG_LTE_LC_PDN_MODULE)
static volatile bool pdn_active;
#else
static volatile bool pdn_active = true;
#endif

/* GNSS only runs when LTE leaves the radio alone, so the two facts that explain
 * a starved GNSS are whether we are stuck in RRC connected and whether the
 * network actually granted PSM. Both are set from the LTE callback thread. */
static volatile bool rrc_connected;
static volatile int  psm_tau_s    = -1;
static volatile int  psm_active_s = -1; /* -1 = PSM not granted */

/* When the last publish went out. The LTE handler uses it to log how long RRC
 * stayed connected after we finished sending -- the tail RAI should shrink. */
static volatile int64_t last_pub_ms;

static char device_id[HW_ID_LEN];

/* ── GNSS ─────────────────────────────────────────────────────────  */
/* Set by EVT_BLOCKED/UNBLOCKED; the handler runs in ISR context, so it only
 * flags the change and the main loop logs the edge. */
static volatile bool gnss_blocked;

static void gnss_handler(int event)
{
	switch (event) {
	case NRF_MODEM_GNSS_EVT_PVT:
		if (nrf_modem_gnss_read(&pvt, sizeof(pvt),
					NRF_MODEM_GNSS_DATA_PVT) == 0) {
			k_sem_give(&pvt_sem);
		}
		break;
	case NRF_MODEM_GNSS_EVT_BLOCKED:
		gnss_blocked = true;
		break;
	case NRF_MODEM_GNSS_EVT_UNBLOCKED:
		gnss_blocked = false;
		break;
	default:
		break;
	}
}

/* Set up GNSS without starting it: loc_fsm decides when it may run. */
static int gnss_configure(void)
{
	int err;

	err = nrf_modem_gnss_event_handler_set(gnss_handler);
	if (err) {
		LOG_ERR("gnss event handler: %d", err);
		return err;
	}

	uint16_t nmea_mask = 0; /* no NMEA — we use PVT only */
	nrf_modem_gnss_nmea_mask_set(nmea_mask);

	nrf_modem_gnss_fix_interval_set(GNSS_INTERVAL_S);
	nrf_modem_gnss_fix_retry_set(0); /* run continuously */

	uint8_t use_case = NRF_MODEM_GNSS_USE_CASE_MULTIPLE_HOT_START;
	nrf_modem_gnss_use_case_set(use_case);

	return 0;
}

static int gnss_start(void)
{
	int err = nrf_modem_gnss_start();

	if (err) {
		LOG_ERR("gnss start: %d", err);
	}
	return err;
}

/* ── LTE ──────────────────────────────────────────────────────────  */
static void lte_handler(const struct lte_lc_evt *const evt)
{
	switch (evt->type) {
	case LTE_LC_EVT_NW_REG_STATUS:
		lte_status = evt->nw_reg_status;
		if (lte_status == LTE_LC_NW_REG_REGISTERED_HOME ||
		    lte_status == LTE_LC_NW_REG_REGISTERED_ROAMING) {
			LOG_INF("LTE registered (%s)",
				lte_status == LTE_LC_NW_REG_REGISTERED_ROAMING
					? "roaming" : "home");
			lte_connected = true;
		} else {
			lte_connected = false;
		}
		break;
	case LTE_LC_EVT_PSM_UPDATE:
		/* active_time == -1 means the network refused PSM. Roaming networks
		 * often do. Without PSM the modem keeps monitoring pagings and GNSS
		 * never gets a long enough window for a cold start. Log at INF: this
		 * was LOG_DBG and therefore invisible at CONFIG_TRACKER_LOG_LEVEL=3. */
		psm_tau_s    = evt->psm_cfg.tau;
		psm_active_s = evt->psm_cfg.active_time;
		if (psm_active_s < 0) {
			LOG_WRN("PSM: NOT granted by network (TAU %d)", psm_tau_s);
		} else {
			LOG_INF("PSM: granted — TAU %d s, active %d s",
				psm_tau_s, psm_active_s);
		}
		break;
#if defined(CONFIG_LTE_LC_PDN_MODULE)
	case LTE_LC_EVT_PDN:
		/* Default-context (CID 0) activation is when we actually have
		 * an IP and sockets can be created. */
		if (evt->pdn.cid == 0) {
			if (evt->pdn.type == LTE_LC_EVT_PDN_ACTIVATED) {
				pdn_active = true;
				LOG_INF("PDN: default context active (IP up)");
			} else if (evt->pdn.type == LTE_LC_EVT_PDN_DEACTIVATED) {
				pdn_active = false;
				LOG_WRN("PDN: default context down");
			}
		}
		break;
#endif
	case LTE_LC_EVT_RRC_UPDATE:
		rrc_connected = (evt->rrc_mode == LTE_LC_RRC_MODE_CONNECTED);
		if (rrc_connected) {
			LOG_INF("RRC: connected (GNSS blocked)");
		} else {
			/* The tail between our last publish and RRC release is
			 * radio time GNSS cannot use. RAI exists to shrink it;
			 * this delta is the measurement of whether it works. */
			int64_t tail = k_uptime_get() - last_pub_ms;

			if (last_pub_ms > 0 && tail < 30000) {
				LOG_INF("RRC: idle (%lld ms after publish)",
					(long long)tail);
			} else {
				LOG_INF("RRC: idle");
			}
		}
		break;
	default:
		break;
	}
}

static const char *lte_status_str(void)
{
	switch (lte_status) {
	case LTE_LC_NW_REG_NOT_REGISTERED:       return "not registered";
	case LTE_LC_NW_REG_REGISTERED_HOME:      return "registered (home)";
	case LTE_LC_NW_REG_SEARCHING:            return "searching";
	case LTE_LC_NW_REG_REGISTRATION_DENIED:  return "denied";
	case LTE_LC_NW_REG_UNKNOWN:              return "no coverage";
	case LTE_LC_NW_REG_REGISTERED_ROAMING:   return "registered (roaming)";
	default:                                  return "?";
	}
}

/* ── cell identity (AT%XMONITOR) ─────────────────────────────────  */
/* Helper: extract the next comma-delimited XMONITOR field, stripping the
 * surrounding quotes if present. Returns the token or NULL. Uses strtok state. */
static char *xmon_field(char *first)
{
	char *f = strtok(first, ",");

	if (f && f[0] == '"') {
		f++;
		char *e = strchr(f, '"');

		if (e) {
			*e = '\0';
		}
	}
	return f;
}

/* Read the serving cell from AT%XMONITOR (cached — no radio scan). Fills sc.
 * XMONITOR: <reg>,"<long>","<short>","<plmn>","<tac>",<AcT>,<band>,
 *           "<cell_id>",<phys_cell_id>,<EARFCN>,<rsrp>,<snr>,...
 * PLMN is "MCCMNC" (MCC=first 3 digits); TAC and cell-id are hex strings. */
static int read_serving_cell(struct serving_cell *sc)
{
	char at_resp[256];

	memset(sc, 0, sizeof(*sc));

	if (nrf_modem_at_cmd(at_resp, sizeof(at_resp), "AT%%XMONITOR") != 0) {
		return -EIO;
	}

	char *cp = strchr(at_resp, ':');

	if (!cp) {
		return -EINVAL;
	}
	cp++;

	xmon_field(cp);                    /* 1: reg status */
	char *longn = xmon_field(NULL);    /* 2: long name  */
	xmon_field(NULL);                  /* 3: short name */
	char *plmn = xmon_field(NULL);     /* 4: plmn "MCCMNC" */
	char *tac  = xmon_field(NULL);     /* 5: tac (hex)  */
	xmon_field(NULL);                  /* 6: AcT        */
	char *band = xmon_field(NULL);     /* 7: band       */
	char *cid  = xmon_field(NULL);     /* 8: cell id (hex) */
	xmon_field(NULL);                  /* 9: phys cell  */
	xmon_field(NULL);                  /* 10: EARFCN    */
	char *rsrp = strtok(NULL, ",\r\n");/* 11: rsrp idx  */

	if (!plmn || strlen(plmn) < 5 || !tac || !cid) {
		return -ENODATA;
	}

	/* Split PLMN: MCC = first 3 chars, MNC = the rest (2 or 3 digits). */
	char mcc_buf[4] = { plmn[0], plmn[1], plmn[2], '\0' };

	sc->mcc = atoi(mcc_buf);
	sc->mnc = atoi(plmn + 3);
	sc->tac = strtoul(tac, NULL, 16);
	sc->cid = strtoul(cid, NULL, 16);
	sc->band = band ? atoi(band) : 0;
	sc->rsrp_dbm = rsrp ? RSRP_IDX_TO_DBM(atoi(rsrp)) : 0;
	if (longn) {
		strncpy(sc->op, longn, sizeof(sc->op) - 1);
	}
	sc->valid = true;
	return 0;
}

/* ── status block ─────────────────────────────────────────────────  */
static void print_status(const struct nrf_modem_gnss_pvt_data_frame *p,
			 const struct loc_status *loc, int64_t uptime_ms)
{
	LOG_INF("===== status @ %llds =====", (long long)(uptime_ms / 1000));

	/* LTE status: registration state + serving-cell details (same cached
	 * AT%XMONITOR read used for the cell-location fallback). */
	struct serving_cell sc;

	if (read_serving_cell(&sc) == 0 && sc.valid) {
		LOG_INF("LTE:  %s | op %s | band %d | cell %u | RSRP %d dBm",
			lte_status_str(), sc.op, sc.band, sc.cid, sc.rsrp_dbm);
	} else {
		LOG_INF("LTE:  %s", lte_status_str());
	}

	/* GNSS status */
	if (p->flags & NRF_MODEM_GNSS_PVT_FLAG_FIX_VALID) {
		LOG_INF("GNSS: FIX  %.6f, %.6f  alt %.1fm  acc %.1fm  sats %u/%u",
			p->latitude, p->longitude,
			(double)p->altitude, (double)p->accuracy,
			loc->used, loc->tracked);
	} else {
		LOG_INF("GNSS: searching  flags 0x%02x", p->flags);
		/* These two mean different things and want different fixes:
		 *   DEADLINE_MISSED        no window at all since the last PVT — LTE
		 *                          is transmitting; only backing off LTE helps.
		 *   NOT_ENOUGH_WINDOW_TIME windows exist but are too short — the case
		 *                          nrf_modem_gnss_prio_mode_enable() is for.
		 * The old code tested only the first, so the two looked identical. */
		if (p->flags & NRF_MODEM_GNSS_PVT_FLAG_DEADLINE_MISSED) {
			LOG_WRN("GNSS: no window since last PVT (LTE active)");
		}
		if (p->flags & NRF_MODEM_GNSS_PVT_FLAG_NOT_ENOUGH_WINDOW_TIME) {
			LOG_WRN("GNSS: windows too short (no PSM/eDRX?)");
		}
	}
	loc_fsm_log(loc, p);

	if (psm_active_s < 0) {
		LOG_INF("LTE:  RRC %s | PSM not granted",
			rrc_connected ? "connected" : "idle");
	} else {
		LOG_INF("LTE:  RRC %s | PSM TAU %ds active %ds",
			rrc_connected ? "connected" : "idle",
			psm_tau_s, psm_active_s);
	}

	/* PDN state next to socket state, so a "no socket" that is really
	 * "PDN not up yet" is obvious in the log. */
	LOG_INF("net:  %s | pdn %s", coap_pub_ready() ? "ready" : "no socket",
		pdn_active ? "active" : "down");
}

/* ── main ─────────────────────────────────────────────────────────  */
int main(void)
{
	int err;

	LOG_INF("tracker starting");

	err = nrf_modem_lib_init();
	if (err) {
		LOG_ERR("modem init: %d", err);
		return err;
	}

	/* Device identity: IMEI on hardware, env/Kconfig on native_sim */
	err = hw_id_get(device_id, sizeof(device_id));
	if (err) {
		LOG_ERR("hw_id_get: %d", err);
		return err;
	}
	LOG_INF("device id: %s", device_id);
	LOG_INF("server: coap://%s:%d/obs", SERVER_HOST, SERVER_PORT);
	/* GPS samples land at the publish interval; a track segment's time model
	 * (anchor + i*dt) is built on that cadence. */
	obs_queue_init(device_id, POST_INTERVAL_MS);

	/* Start LTE async — don't block, status loop shows progress */
	LOG_INF("starting LTE (async)...");
	err = lte_lc_connect_async(lte_handler);
	if (err) {
		LOG_ERR("lte_lc_connect_async: %d", err);
		return err;
	}

#if defined(CONFIG_LTE_LC_PDN_MODULE)
	/* Default-context PDN events tell us when the IP is actually up,
	 * not just when we've registered. */
	err = lte_lc_pdn_default_ctx_events_enable();
	if (err) {
		LOG_WRN("pdn events enable: %d", err);
	}
#endif

	/* Configure GNSS but do NOT start it yet. An unregistered modem runs a
	 * continuous cell search; GNSS running against that starves the search and
	 * gains nothing itself. loc_fsm starts it once LTE has registered. */
	err = gnss_configure();
	if (err) {
		LOG_ERR("gnss configure: %d", err);
		return err;
	}
	bool gnss_running = false;
	bool gnss_blocked_prev = false;
	/* lte_lc_connect_async() below turns the stack on; GNSS_EXCLUSIVE is the
	 * only thing that turns it off. */
	bool lte_stack_on = true;
	/* Snapshot of the most recent PVT frame with FIX_VALID set. The live `pvt`
	 * global only carries defined lat/lon while the flag is set, but the FSM
	 * lets us publish for up to GPS_STALE_S after the fix lapses -- those
	 * publishes must come from this copy, not from whatever an unfixed frame
	 * happens to contain. (static: ~700 B, keep off the main stack) */
	static struct nrf_modem_gnss_pvt_data_frame fix_pvt;
	int64_t fix_pvt_ms = 0; /* when fix_pvt was captured, for the age field */

	int64_t last_post_ms   = 0;
	int64_t last_status_ms = 0;
	int64_t next_net_ms    = 0;
	/* Backdated so the FIRST queued observation flushes immediately: a fresh
	 * boot should appear on the map within seconds, not after a full flush
	 * interval. Subsequent flushes then pace at FLUSH_INTERVAL_MS. */
	int64_t last_flush_ms  = -FLUSH_INTERVAL_MS;
	enum loc_state prev_state = LOC_LTE_ATTACH;
	struct loc_status loc;

	loc_fsm_init(k_uptime_get());

	for (;;) {
		/* Wait for next PVT event (1 Hz) with a 2s timeout so the
		 * status block still prints even if GNSS is blocked by LTE. */
		k_sem_take(&pvt_sem, K_SECONDS(2));

		int64_t now = k_uptime_get();

		if (pvt.flags & NRF_MODEM_GNSS_PVT_FLAG_FIX_VALID) {
			fix_pvt = pvt;
			fix_pvt_ms = now;
		}

		/* Policy first: it owns the fix-staleness and ephemeris bookkeeping. */
		loc_fsm_update(&pvt, now, lte_connected, &loc);

		/* Run GNSS only when the FSM says so. While the modem is searching
		 * for a network the search owns the radio, and GNSS alongside it just
		 * flip-flops between a few tracked satellites and none. */
		if (loc.gnss_wanted && !gnss_running) {
			LOG_INF("starting GNSS");
			if (gnss_start() == 0) {
				gnss_running = true;
			}
		} else if (!loc.gnss_wanted && gnss_running) {
			LOG_INF("LTE lost — stopping GNSS until re-registered");
			(void)nrf_modem_gnss_stop();
			gnss_running = false;
		}

		/* GNSS_EXCLUSIVE: take the LTE stack down entirely so idle-mode
		 * DRX/reselection can't slice GNSS; bring it back on exit. GNSS
		 * keeps running across both edges — DEACTIVATE_LTE leaves it be. */
		if (!loc.lte_wanted && lte_stack_on) {
			LOG_WRN("deactivating LTE — GNSS gets the radio outright");
			if (lte_lc_func_mode_set(LTE_LC_FUNC_MODE_DEACTIVATE_LTE) == 0) {
				lte_stack_on = false;
			}
			coap_pub_close(); /* socket dies with the PDN */
		} else if (loc.lte_wanted && !lte_stack_on) {
			LOG_INF("re-activating LTE (re-attach follows)");
			if (lte_lc_func_mode_set(LTE_LC_FUNC_MODE_ACTIVATE_LTE) == 0) {
				lte_stack_on = true;
			}
		}

		/* A PDN drop (deactivation or network-side) orphans the UDP socket;
		 * recreate it when the PDN returns rather than sending into a void. */
		if (!pdn_active && coap_pub_ready()) {
			LOG_WRN("PDN down — closing CoAP socket");
			coap_pub_close();
		}

		/* EVT_BLOCKED/UNBLOCKED arrive in ISR context; log the edge here. */
		if (gnss_blocked != gnss_blocked_prev) {
			gnss_blocked_prev = gnss_blocked;
			LOG_INF("GNSS: %s by LTE",
				gnss_blocked ? "blocked" : "unblocked");
		}

		/* One-time UDP socket setup, retried on failure. Needs LTE up (DNS
		 * goes over the PDN) and is gated on publish_allowed so even the
		 * getaddrinfo exchange stays out of GNSS quiet windows. There is no
		 * connection to keep alive: UDP is silent between sends by nature,
		 * which is the whole point of the CoAP move. Gated on pdn_active
		 * too: before the default PDN has an IP, getaddrinfo/socket can
		 * only fail. (Always true on native_sim.) */
		if (loc.publish_allowed && pdn_active &&
		    lte_connected && !coap_pub_ready() && now >= next_net_ms) {
			next_net_ms = now + NET_RETRY_MS;
			if (coap_pub_init(SERVER_HOST, SERVER_PORT)) {
				LOG_WRN("CoAP setup failed (retry in %d s)",
					NET_RETRY_MS / 1000);
			}
		}

		/* Status block every STATUS_INTERVAL_MS */
		if (now - last_status_ms >= STATUS_INTERVAL_MS) {
			last_status_ms = now;
			print_status(&pvt, &loc, now);
		}

		/* SAMPLE at the FSM's cadence — free, no radio involved. GPS
		 * samples come from the fix-valid snapshot; within ~10 m of the
		 * previous point they queue as 4 B repeat entries. */
		if (loc.publish_allowed && now - last_post_ms >= loc.publish_interval_ms) {
			last_post_ms = now;
			if (!loc.prefer_cell) {
				obs_queue_add_gps(&fix_pvt, fix_pvt_ms);
			} else if (lte_connected) {
				struct serving_cell sc;

				if (read_serving_cell(&sc) == 0 && sc.valid) {
					obs_queue_add_cell(sc.mcc, sc.mnc, sc.tac,
							   sc.cid, sc.rsrp_dbm, now);
				} else {
					LOG_WRN("serving cell unavailable");
				}
			}
		}

		/* FLUSH the queue as one datagram. Time-based normally; immediately
		 * on a state change (a fresh fix or a boot cell report must reach
		 * the map now, not in two minutes) and in REPORT_CELL, whose whole
		 * purpose is promptness. Radio use needs publish_allowed. */
		bool state_changed = (loc.state != prev_state);

		prev_state = loc.state;
		if (obs_queue_len() > 0 && loc.publish_allowed && coap_pub_ready() &&
		    (state_changed || loc.state == LOC_REPORT_CELL ||
		     obs_queue_len() >= 20 ||
		     now - last_flush_ms >= FLUSH_INTERVAL_MS)) {
			bool had_cell = obs_queue_has_cell();

			if (obs_queue_flush(now) == 0) {
				last_flush_ms = now;
				last_pub_ms = now; /* RRC-tail measurement */
				if (had_cell) {
					/* Coarse position is on the map; the FSM
					 * may now take the radio for GNSS. */
					loc_fsm_note_cell_sent();
				}
			}
		}
	}

	return 0;
}
