# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtracker.proto\"y\n\x06GpsFix\x12\x0e\n\x06lat_e7\x18\x01 \x01(\x11\x12\x0e\n\x06lon_e7\x18\x02 \x01(\x11\x12\x0e\n\x06\x61lt_dm\x18\x03 \x01(\x11\x12\x0e\n\x06\x61\x63\x63_dm\x18\x04 \x01(\r\x12\x0f\n\x07spd_dms\x18\x05 \x01(\r\x12\x10\n\x08hdg_ddeg\x18\x06 \x01(\r\x12\x0c\n\x04sats\x18\x07 \x01(\r\"o\n\x0cTrackSegment\x12\x17\n\x06\x61nchor\x18\x01 \x01(\x0b\x32\x07.GpsFix\x12\r\n\x05\x64t_ms\x18\x02 \x01(\r\x12\x10\n\x04\x64lat\x18\x03 \x03(\x11\x42\x02\x10\x01\x12\x10\n\x04\x64lon\x18\x04 \x03(\x11\x42\x02\x10\x01\x12\x13\n\x07spd_dms\x18\x05 \x03(\rB\x02\x10\x01\"S\n\x07\x43\x65llFix\x12\x0b\n\x03mcc\x18\x01 \x01(\r\x12\x0b\n\x03mnc\x18\x02 \x01(\r\x12\x0b\n\x03tac\x18\x03 \x01(\r\x12\x0f\n\x07\x63\x65ll_id\x18\x04 \x01(\r\x12\x10\n\x08rsrp_dbm\x18\x05 \x01(\x11\"E\n\x07LogLine\x12\r\n\x05\x61ge_s\x18\x01 \x01(\r\x12\r\n\x05level\x18\x02 \x01(\r\x12\x0e\n\x06module\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\"#\n\x08LogBatch\x12\x17\n\x05lines\x18\x01 \x03(\x0b\x32\x08.LogLine\"r\n\x05\x45ntry\x12\r\n\x05\x61ge_s\x18\x01 \x01(\r\x12\x1e\n\x05track\x18\x02 \x01(\x0b\x32\r.TrackSegmentH\x00\x12\x18\n\x04\x63\x65ll\x18\x03 \x01(\x0b\x32\x08.CellFixH\x00\x12\x18\n\x03log\x18\x04 \x01(\x0b\x32\t.LogBatchH\x00\x42\x06\n\x04kind\"B\n\x03Obs\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x17\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x06.Entryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKSEGMENT'].fields_by_name['dlat']._loaded_options = None
  _globals['_TRACKSEGMENT'].fields_by_name['dlat']._serialized_options = b'\020\001'
  _globals['_TRACKSEGMENT'].fields_by_name['dlon']._loaded_options = None
  _globals['_TRACKSEGMENT'].fields_by_name['dlon']._serialized_options = b'\020\001'
  _globals['_TRACKSEGMENT'].fields_by_name['spd_dms']._loaded_options = None
  _globals['_TRACKSEGMENT'].fields_by_name['spd_dms']._serialized_options = b'\020\001'
  _globals['_GPSFIX']._serialized_start=17
  _globals['_GPSFIX']._serialized_end=138
  _globals['_TRACKSEGMENT']._serialized_start=140
  _globals['_TRACKSEGMENT']._serialized_end=251
  _globals['_CELLFIX']._serialized_start=253
  _globals['_CELLFIX']._serialized_end=336
  _globals['_LOGLINE']._serialized_start=338
  _globals['_LOGLINE']._serialized_end=407
  _globals['_LOGBATCH']._serialized_start=409
  _globals['_LOGBATCH']._serialized_end=444
  _globals['_ENTRY']._serialized_start=446
  _globals['_ENTRY']._serialized_end=560
  _globals['_OBS']._serialized_start=562
  _globals['_OBS']._serialized_end=628
# @@protoc_insertion_point(module_scope)
