/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tracker.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GpsFix, GpsFix, AUTO)


PB_BIND(TrackSegment, TrackSegment, AUTO)


PB_BIND(CellFix, CellFix, AUTO)


PB_BIND(LogLine, LogLine, AUTO)


PB_BIND(LogBatch, LogBatch, AUTO)


PB_BIND(Entry, Entry, AUTO)


PB_BIND(Obs, Obs, AUTO)


PB_BIND(AgnssRequest, AgnssRequest, AUTO)


PB_BIND(AgnssTime, AgnssTime, AUTO)


PB_BIND(AgnssLocation, AgnssLocation, AUTO)


PB_BIND(AgnssUtc, AgnssUtc, AUTO)


PB_BIND(AgnssKlobuchar, AgnssKlobuchar, AUTO)


PB_BIND(AgnssEphemeris, AgnssEphemeris, AUTO)


PB_BIND(AgnssData, AgnssData, AUTO)



