/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TRACKER_PB_H_INCLUDED
#define PB_TRACKER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Full GNSS fix. Used as a track segment's anchor (absolute position); a lone
 fix is just a TrackSegment with empty delta arrays. */
typedef struct _GpsFix {
    int32_t lat_e7; /* degrees * 1e7 */
    int32_t lon_e7; /* degrees * 1e7 */
    int32_t alt_dm; /* decimetres */
    uint32_t acc_dm; /* decimetres */
    uint32_t spd_dms; /* dm/s */
    uint32_t hdg_ddeg; /* tenths of a degree */
    uint32_t sats; /* satellites used */
} GpsFix;

/* A run of GNSS positions at a fixed cadence. The anchor is point 0 (absolute);
 dlat[i]/dlon[i]/spd_dms[i] describe point i+1 (i.e. the arrays parallel each
 other and are all the same length = point_count - 1). Deltas are in
 1e-7-degree units, zigzag varint: small (slow / high-rate) deltas cost 1 B,
 typical driving deltas 2 B. Overflow-free by construction: the firmware
 starts a fresh segment (new anchor) before any delta would exceed a tick's
 real range. A stationary run is simply zero deltas (folds in v2's "repeat"
 entry) -- note a zero point costs 2 B on the wire (1 B in dlat + 1 B in dlon),
 not 1.

 spd_dms carries the GNSS-measured (Doppler) speed per point. This is NOT
 derived from the position deltas on the server: at 1 Hz that derivation
 carries ~8 km/h of jitter and at 10 Hz it is unusable (a stationary unit
 would show a phantom ~70 km/h from position noise alone). Doppler speed is
 filtered and costs ~1-2 B/point, so we send it. Being a packed array it may
 be left empty (0 B) in a future low-bandwidth mode; the server then falls
 back to a coarse derived speed. */
typedef struct _TrackSegment {
    bool has_anchor;
    GpsFix anchor;
    uint32_t dt_ms; /* spacing between points */
    pb_callback_t dlat;
    pb_callback_t dlon;
    pb_callback_t spd_dms; /* GNSS Doppler speed, dm/s */
} TrackSegment;

/* Serving-cell observation (no GNSS, or a stationary keepalive). The server
 resolves this to an approximate location. */
typedef struct _CellFix {
    uint32_t mcc;
    uint32_t mnc;
    uint32_t tac;
    uint32_t cell_id; /* 28-bit ECI */
    int32_t rsrp_dbm;
    uint32_t act; /* 3GPP access technology: 7 = LTE-M, 9 = NB-IoT */
} CellFix;

/* One device log line. level uses Zephyr's numbering (1=ERR 2=WRN 3=INF
 4=DBG); age_s dates the line the same way observations are dated. Text
 stays plain text: log volume at the uplink threshold is small, and a
 greppable wire beats a tokenizer toolchain. */
typedef struct _LogLine {
    uint32_t age_s;
    uint32_t level;
    pb_callback_t module;
    pb_callback_t text;
} LogLine;

typedef struct _LogBatch {
    pb_callback_t lines;
} LogBatch;

/* One item in a batch. age_s ages the anchor (track) or the fix (cell);
 log lines carry their own ages (a batch spans time).
 A thing worth telling a human about, right now. Today the only kind is an
 accelerometer wake on a quiescent tracker: "your asset moved". It jumps the
 uplink queue (prio 0) and rides the urgent flush the FSM transition fires. */
typedef struct _MotionEvent {
    uint32_t age_s;
    uint32_t reason; /* 1 = IMU wake */
} MotionEvent;

typedef struct _Entry {
    uint32_t age_s;
    pb_size_t which_kind;
    union _Entry_kind {
        TrackSegment track;
        CellFix cell;
        LogBatch log;
        MotionEvent motion;
    } kind;
} Entry;

/* The datagram. version+device_id are shared by every entry in the batch. */
typedef struct _Obs {
    uint32_t version; /* 3 */
    pb_callback_t device_id; /* IMEI on hardware, TRACKER_DEVICE_ID on the sim */
    pb_callback_t entries;
} Obs;

/* Forwarded from the modem's own need report (nrf_modem_gnss_agnss_expiry). */
typedef struct _AgnssRequest {
    char device_id[24]; /* lets the server pick a location + elevation-filter */
    uint32_t data_flags; /* NRF_MODEM_GNSS_AGNSS_*_REQUEST bits */
    uint64_t sv_mask_ephe; /* bit n-1 = PRN n needs ephemeris (informational) */
} AgnssRequest;

/* GPS system time, computed from the server's NTP-disciplined clock.
 date_day = days since the GPS epoch (6 Jan 1980); time_full_s/frac_ms =
 GPS time of day (UTC + leap seconds). Semantics identical to Nordic's
 assistance samples. */
typedef struct _AgnssTime {
    uint32_t date_day;
    uint32_t time_full_s;
    uint32_t time_frac_ms;
} AgnssTime;

/* Coarse position seed: the device's last known position from the server DB,
 uncertainty inflated with age. Encodings are the 3GPP ones the modem
 expects (lat: deg*2^23/90, lon: deg*2^24/360, unc: K in r=10*(1.1^K-1) m). */
typedef struct _AgnssLocation {
    int32_t latitude;
    int32_t longitude;
    int32_t altitude; /* metres; unc_altitude=255 marks it unknown */
    uint32_t unc_semimajor;
    uint32_t unc_semiminor;
    uint32_t unc_altitude;
    uint32_t confidence; /* percent */
} AgnssLocation;

/* GPS-UTC parameters (RINEX header GPUT/LEAP when present). */
typedef struct _AgnssUtc {
    int32_t a1; /* 2^-50 s/s */
    int32_t a0; /* 2^-30 s */
    uint32_t tot; /* 2^12 s */
    uint32_t wn_t; /* week mod 256 */
    int32_t delta_tls; /* leap seconds */
    uint32_t wn_lsf;
    int32_t dn;
    int32_t delta_tlsf;
} AgnssUtc;

/* Klobuchar ionosphere (RINEX header GPSA/GPSB when present). */
typedef struct _AgnssKlobuchar {
    int32_t alpha0; /* 2^-30 s */
    int32_t alpha1; /* 2^-27 s/sc */
    int32_t alpha2; /* 2^-24 s/sc^2 */
    int32_t alpha3; /* 2^-24 s/sc^3 */
    int32_t beta0; /* 2^11 s */
    int32_t beta1; /* 2^14 s/sc */
    int32_t beta2; /* 2^16 s/sc^2 */
    int32_t beta3; /* 2^16 s/sc^3 */
} AgnssKlobuchar;

/* One GPS LNAV ephemeris, ICD-200 scaled integers matching
 struct nrf_modem_gnss_agnss_gps_data_ephemeris field-for-field. */
typedef struct _AgnssEphemeris {
    uint32_t sv_id;
    uint32_t health;
    uint32_t iodc; /* 11 bits */
    uint32_t toc; /* 2^4 s */
    int32_t af2; /* 2^-55 */
    int32_t af1; /* 2^-43 */
    int32_t af0; /* 2^-31 */
    int32_t tgd; /* 2^-31 s */
    uint32_t ura; /* URA index 0..15 */
    uint32_t fit_int; /* 0: 4 h, 1: >4 h */
    uint32_t toe; /* 2^4 s */
    int32_t w; /* 2^-31 semi-circle */
    int32_t delta_n; /* 2^-43 sc/s */
    int32_t m0; /* 2^-31 sc */
    int32_t omega_dot; /* 2^-43 sc/s */
    uint32_t e; /* 2^-33 */
    int32_t idot; /* 2^-43 sc/s */
    uint32_t sqrt_a; /* 2^-19 sqrt(m) */
    int32_t i0; /* 2^-31 sc */
    int32_t omega0; /* 2^-31 sc */
    int32_t crs; /* 2^-5 m */
    int32_t cis; /* 2^-29 rad */
    int32_t cus; /* 2^-29 rad */
    int32_t crc; /* 2^-5 m */
    int32_t cic; /* 2^-29 rad */
    int32_t cuc; /* 2^-29 rad */
} AgnssEphemeris;

/* The response payload. Every present element gets its own
 nrf_modem_gnss_agnss_write(); ephemerides are written one element at a
 time (nanopb decode callback — never an array on the stack). */
typedef struct _AgnssData {
    bool has_time;
    AgnssTime time;
    bool has_location;
    AgnssLocation location;
    bool has_utc;
    AgnssUtc utc;
    bool has_klobuchar;
    AgnssKlobuchar klobuchar;
    pb_callback_t ephemeris;
} AgnssData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GpsFix_init_default                      {0, 0, 0, 0, 0, 0, 0}
#define TrackSegment_init_default                {false, GpsFix_init_default, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define CellFix_init_default                     {0, 0, 0, 0, 0, 0}
#define LogLine_init_default                     {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define LogBatch_init_default                    {{{NULL}, NULL}}
#define MotionEvent_init_default                 {0, 0}
#define Entry_init_default                       {0, 0, {TrackSegment_init_default}}
#define Obs_init_default                         {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AgnssRequest_init_default                {"", 0, 0}
#define AgnssTime_init_default                   {0, 0, 0}
#define AgnssLocation_init_default               {0, 0, 0, 0, 0, 0, 0}
#define AgnssUtc_init_default                    {0, 0, 0, 0, 0, 0, 0, 0}
#define AgnssKlobuchar_init_default              {0, 0, 0, 0, 0, 0, 0, 0}
#define AgnssEphemeris_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AgnssData_init_default                   {false, AgnssTime_init_default, false, AgnssLocation_init_default, false, AgnssUtc_init_default, false, AgnssKlobuchar_init_default, {{NULL}, NULL}}
#define GpsFix_init_zero                         {0, 0, 0, 0, 0, 0, 0}
#define TrackSegment_init_zero                   {false, GpsFix_init_zero, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define CellFix_init_zero                        {0, 0, 0, 0, 0, 0}
#define LogLine_init_zero                        {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define LogBatch_init_zero                       {{{NULL}, NULL}}
#define MotionEvent_init_zero                    {0, 0}
#define Entry_init_zero                          {0, 0, {TrackSegment_init_zero}}
#define Obs_init_zero                            {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AgnssRequest_init_zero                   {"", 0, 0}
#define AgnssTime_init_zero                      {0, 0, 0}
#define AgnssLocation_init_zero                  {0, 0, 0, 0, 0, 0, 0}
#define AgnssUtc_init_zero                       {0, 0, 0, 0, 0, 0, 0, 0}
#define AgnssKlobuchar_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0}
#define AgnssEphemeris_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AgnssData_init_zero                      {false, AgnssTime_init_zero, false, AgnssLocation_init_zero, false, AgnssUtc_init_zero, false, AgnssKlobuchar_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GpsFix_lat_e7_tag                        1
#define GpsFix_lon_e7_tag                        2
#define GpsFix_alt_dm_tag                        3
#define GpsFix_acc_dm_tag                        4
#define GpsFix_spd_dms_tag                       5
#define GpsFix_hdg_ddeg_tag                      6
#define GpsFix_sats_tag                          7
#define TrackSegment_anchor_tag                  1
#define TrackSegment_dt_ms_tag                   2
#define TrackSegment_dlat_tag                    3
#define TrackSegment_dlon_tag                    4
#define TrackSegment_spd_dms_tag                 5
#define CellFix_mcc_tag                          1
#define CellFix_mnc_tag                          2
#define CellFix_tac_tag                          3
#define CellFix_cell_id_tag                      4
#define CellFix_rsrp_dbm_tag                     5
#define CellFix_act_tag                          6
#define LogLine_age_s_tag                        1
#define LogLine_level_tag                        2
#define LogLine_module_tag                       3
#define LogLine_text_tag                         4
#define LogBatch_lines_tag                       1
#define MotionEvent_age_s_tag                    1
#define MotionEvent_reason_tag                   2
#define Entry_age_s_tag                          1
#define Entry_track_tag                          2
#define Entry_cell_tag                           3
#define Entry_log_tag                            4
#define Entry_motion_tag                         5
#define Obs_version_tag                          1
#define Obs_device_id_tag                        2
#define Obs_entries_tag                          3
#define AgnssRequest_device_id_tag               1
#define AgnssRequest_data_flags_tag              2
#define AgnssRequest_sv_mask_ephe_tag            3
#define AgnssTime_date_day_tag                   1
#define AgnssTime_time_full_s_tag                2
#define AgnssTime_time_frac_ms_tag               3
#define AgnssLocation_latitude_tag               1
#define AgnssLocation_longitude_tag              2
#define AgnssLocation_altitude_tag               3
#define AgnssLocation_unc_semimajor_tag          4
#define AgnssLocation_unc_semiminor_tag          5
#define AgnssLocation_unc_altitude_tag           6
#define AgnssLocation_confidence_tag             7
#define AgnssUtc_a1_tag                          1
#define AgnssUtc_a0_tag                          2
#define AgnssUtc_tot_tag                         3
#define AgnssUtc_wn_t_tag                        4
#define AgnssUtc_delta_tls_tag                   5
#define AgnssUtc_wn_lsf_tag                      6
#define AgnssUtc_dn_tag                          7
#define AgnssUtc_delta_tlsf_tag                  8
#define AgnssKlobuchar_alpha0_tag                1
#define AgnssKlobuchar_alpha1_tag                2
#define AgnssKlobuchar_alpha2_tag                3
#define AgnssKlobuchar_alpha3_tag                4
#define AgnssKlobuchar_beta0_tag                 5
#define AgnssKlobuchar_beta1_tag                 6
#define AgnssKlobuchar_beta2_tag                 7
#define AgnssKlobuchar_beta3_tag                 8
#define AgnssEphemeris_sv_id_tag                 1
#define AgnssEphemeris_health_tag                2
#define AgnssEphemeris_iodc_tag                  3
#define AgnssEphemeris_toc_tag                   4
#define AgnssEphemeris_af2_tag                   5
#define AgnssEphemeris_af1_tag                   6
#define AgnssEphemeris_af0_tag                   7
#define AgnssEphemeris_tgd_tag                   8
#define AgnssEphemeris_ura_tag                   9
#define AgnssEphemeris_fit_int_tag               10
#define AgnssEphemeris_toe_tag                   11
#define AgnssEphemeris_w_tag                     12
#define AgnssEphemeris_delta_n_tag               13
#define AgnssEphemeris_m0_tag                    14
#define AgnssEphemeris_omega_dot_tag             15
#define AgnssEphemeris_e_tag                     16
#define AgnssEphemeris_idot_tag                  17
#define AgnssEphemeris_sqrt_a_tag                18
#define AgnssEphemeris_i0_tag                    19
#define AgnssEphemeris_omega0_tag                20
#define AgnssEphemeris_crs_tag                   21
#define AgnssEphemeris_cis_tag                   22
#define AgnssEphemeris_cus_tag                   23
#define AgnssEphemeris_crc_tag                   24
#define AgnssEphemeris_cic_tag                   25
#define AgnssEphemeris_cuc_tag                   26
#define AgnssData_time_tag                       1
#define AgnssData_location_tag                   2
#define AgnssData_utc_tag                        3
#define AgnssData_klobuchar_tag                  4
#define AgnssData_ephemeris_tag                  5

/* Struct field encoding specification for nanopb */
#define GpsFix_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   lat_e7,            1) \
X(a, STATIC,   SINGULAR, SINT32,   lon_e7,            2) \
X(a, STATIC,   SINGULAR, SINT32,   alt_dm,            3) \
X(a, STATIC,   SINGULAR, UINT32,   acc_dm,            4) \
X(a, STATIC,   SINGULAR, UINT32,   spd_dms,           5) \
X(a, STATIC,   SINGULAR, UINT32,   hdg_ddeg,          6) \
X(a, STATIC,   SINGULAR, UINT32,   sats,              7)
#define GpsFix_CALLBACK NULL
#define GpsFix_DEFAULT NULL

#define TrackSegment_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  anchor,            1) \
X(a, STATIC,   SINGULAR, UINT32,   dt_ms,             2) \
X(a, CALLBACK, REPEATED, SINT32,   dlat,              3) \
X(a, CALLBACK, REPEATED, SINT32,   dlon,              4) \
X(a, CALLBACK, REPEATED, UINT32,   spd_dms,           5)
#define TrackSegment_CALLBACK pb_default_field_callback
#define TrackSegment_DEFAULT NULL
#define TrackSegment_anchor_MSGTYPE GpsFix

#define CellFix_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mcc,               1) \
X(a, STATIC,   SINGULAR, UINT32,   mnc,               2) \
X(a, STATIC,   SINGULAR, UINT32,   tac,               3) \
X(a, STATIC,   SINGULAR, UINT32,   cell_id,           4) \
X(a, STATIC,   SINGULAR, SINT32,   rsrp_dbm,          5) \
X(a, STATIC,   SINGULAR, UINT32,   act,               6)
#define CellFix_CALLBACK NULL
#define CellFix_DEFAULT NULL

#define LogLine_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   age_s,             1) \
X(a, STATIC,   SINGULAR, UINT32,   level,             2) \
X(a, CALLBACK, SINGULAR, STRING,   module,            3) \
X(a, CALLBACK, SINGULAR, STRING,   text,              4)
#define LogLine_CALLBACK pb_default_field_callback
#define LogLine_DEFAULT NULL

#define LogBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  lines,             1)
#define LogBatch_CALLBACK pb_default_field_callback
#define LogBatch_DEFAULT NULL
#define LogBatch_lines_MSGTYPE LogLine

#define MotionEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   age_s,             1) \
X(a, STATIC,   SINGULAR, UINT32,   reason,            2)
#define MotionEvent_CALLBACK NULL
#define MotionEvent_DEFAULT NULL

#define Entry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   age_s,             1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,track,kind.track),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,cell,kind.cell),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,log,kind.log),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,motion,kind.motion),   5)
#define Entry_CALLBACK NULL
#define Entry_DEFAULT NULL
#define Entry_kind_track_MSGTYPE TrackSegment
#define Entry_kind_cell_MSGTYPE CellFix
#define Entry_kind_log_MSGTYPE LogBatch
#define Entry_kind_motion_MSGTYPE MotionEvent

#define Obs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           3)
#define Obs_CALLBACK pb_default_field_callback
#define Obs_DEFAULT NULL
#define Obs_entries_MSGTYPE Entry

#define AgnssRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   data_flags,        2) \
X(a, STATIC,   SINGULAR, UINT64,   sv_mask_ephe,      3)
#define AgnssRequest_CALLBACK NULL
#define AgnssRequest_DEFAULT NULL

#define AgnssTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   date_day,          1) \
X(a, STATIC,   SINGULAR, UINT32,   time_full_s,       2) \
X(a, STATIC,   SINGULAR, UINT32,   time_frac_ms,      3)
#define AgnssTime_CALLBACK NULL
#define AgnssTime_DEFAULT NULL

#define AgnssLocation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   latitude,          1) \
X(a, STATIC,   SINGULAR, SINT32,   longitude,         2) \
X(a, STATIC,   SINGULAR, SINT32,   altitude,          3) \
X(a, STATIC,   SINGULAR, UINT32,   unc_semimajor,     4) \
X(a, STATIC,   SINGULAR, UINT32,   unc_semiminor,     5) \
X(a, STATIC,   SINGULAR, UINT32,   unc_altitude,      6) \
X(a, STATIC,   SINGULAR, UINT32,   confidence,        7)
#define AgnssLocation_CALLBACK NULL
#define AgnssLocation_DEFAULT NULL

#define AgnssUtc_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   a1,                1) \
X(a, STATIC,   SINGULAR, SINT32,   a0,                2) \
X(a, STATIC,   SINGULAR, UINT32,   tot,               3) \
X(a, STATIC,   SINGULAR, UINT32,   wn_t,              4) \
X(a, STATIC,   SINGULAR, SINT32,   delta_tls,         5) \
X(a, STATIC,   SINGULAR, UINT32,   wn_lsf,            6) \
X(a, STATIC,   SINGULAR, SINT32,   dn,                7) \
X(a, STATIC,   SINGULAR, SINT32,   delta_tlsf,        8)
#define AgnssUtc_CALLBACK NULL
#define AgnssUtc_DEFAULT NULL

#define AgnssKlobuchar_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   alpha0,            1) \
X(a, STATIC,   SINGULAR, SINT32,   alpha1,            2) \
X(a, STATIC,   SINGULAR, SINT32,   alpha2,            3) \
X(a, STATIC,   SINGULAR, SINT32,   alpha3,            4) \
X(a, STATIC,   SINGULAR, SINT32,   beta0,             5) \
X(a, STATIC,   SINGULAR, SINT32,   beta1,             6) \
X(a, STATIC,   SINGULAR, SINT32,   beta2,             7) \
X(a, STATIC,   SINGULAR, SINT32,   beta3,             8)
#define AgnssKlobuchar_CALLBACK NULL
#define AgnssKlobuchar_DEFAULT NULL

#define AgnssEphemeris_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sv_id,             1) \
X(a, STATIC,   SINGULAR, UINT32,   health,            2) \
X(a, STATIC,   SINGULAR, UINT32,   iodc,              3) \
X(a, STATIC,   SINGULAR, UINT32,   toc,               4) \
X(a, STATIC,   SINGULAR, SINT32,   af2,               5) \
X(a, STATIC,   SINGULAR, SINT32,   af1,               6) \
X(a, STATIC,   SINGULAR, SINT32,   af0,               7) \
X(a, STATIC,   SINGULAR, SINT32,   tgd,               8) \
X(a, STATIC,   SINGULAR, UINT32,   ura,               9) \
X(a, STATIC,   SINGULAR, UINT32,   fit_int,          10) \
X(a, STATIC,   SINGULAR, UINT32,   toe,              11) \
X(a, STATIC,   SINGULAR, SINT32,   w,                12) \
X(a, STATIC,   SINGULAR, SINT32,   delta_n,          13) \
X(a, STATIC,   SINGULAR, SINT32,   m0,               14) \
X(a, STATIC,   SINGULAR, SINT32,   omega_dot,        15) \
X(a, STATIC,   SINGULAR, UINT32,   e,                16) \
X(a, STATIC,   SINGULAR, SINT32,   idot,             17) \
X(a, STATIC,   SINGULAR, UINT32,   sqrt_a,           18) \
X(a, STATIC,   SINGULAR, SINT32,   i0,               19) \
X(a, STATIC,   SINGULAR, SINT32,   omega0,           20) \
X(a, STATIC,   SINGULAR, SINT32,   crs,              21) \
X(a, STATIC,   SINGULAR, SINT32,   cis,              22) \
X(a, STATIC,   SINGULAR, SINT32,   cus,              23) \
X(a, STATIC,   SINGULAR, SINT32,   crc,              24) \
X(a, STATIC,   SINGULAR, SINT32,   cic,              25) \
X(a, STATIC,   SINGULAR, SINT32,   cuc,              26)
#define AgnssEphemeris_CALLBACK NULL
#define AgnssEphemeris_DEFAULT NULL

#define AgnssData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  location,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  utc,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  klobuchar,         4) \
X(a, CALLBACK, REPEATED, MESSAGE,  ephemeris,         5)
#define AgnssData_CALLBACK pb_default_field_callback
#define AgnssData_DEFAULT NULL
#define AgnssData_time_MSGTYPE AgnssTime
#define AgnssData_location_MSGTYPE AgnssLocation
#define AgnssData_utc_MSGTYPE AgnssUtc
#define AgnssData_klobuchar_MSGTYPE AgnssKlobuchar
#define AgnssData_ephemeris_MSGTYPE AgnssEphemeris

extern const pb_msgdesc_t GpsFix_msg;
extern const pb_msgdesc_t TrackSegment_msg;
extern const pb_msgdesc_t CellFix_msg;
extern const pb_msgdesc_t LogLine_msg;
extern const pb_msgdesc_t LogBatch_msg;
extern const pb_msgdesc_t MotionEvent_msg;
extern const pb_msgdesc_t Entry_msg;
extern const pb_msgdesc_t Obs_msg;
extern const pb_msgdesc_t AgnssRequest_msg;
extern const pb_msgdesc_t AgnssTime_msg;
extern const pb_msgdesc_t AgnssLocation_msg;
extern const pb_msgdesc_t AgnssUtc_msg;
extern const pb_msgdesc_t AgnssKlobuchar_msg;
extern const pb_msgdesc_t AgnssEphemeris_msg;
extern const pb_msgdesc_t AgnssData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GpsFix_fields &GpsFix_msg
#define TrackSegment_fields &TrackSegment_msg
#define CellFix_fields &CellFix_msg
#define LogLine_fields &LogLine_msg
#define LogBatch_fields &LogBatch_msg
#define MotionEvent_fields &MotionEvent_msg
#define Entry_fields &Entry_msg
#define Obs_fields &Obs_msg
#define AgnssRequest_fields &AgnssRequest_msg
#define AgnssTime_fields &AgnssTime_msg
#define AgnssLocation_fields &AgnssLocation_msg
#define AgnssUtc_fields &AgnssUtc_msg
#define AgnssKlobuchar_fields &AgnssKlobuchar_msg
#define AgnssEphemeris_fields &AgnssEphemeris_msg
#define AgnssData_fields &AgnssData_msg

/* Maximum encoded size of messages (where known) */
/* TrackSegment_size depends on runtime parameters */
/* LogLine_size depends on runtime parameters */
/* LogBatch_size depends on runtime parameters */
/* Entry_size depends on runtime parameters */
/* Obs_size depends on runtime parameters */
/* AgnssData_size depends on runtime parameters */
#define AgnssEphemeris_size                      167
#define AgnssKlobuchar_size                      48
#define AgnssLocation_size                       42
#define AgnssRequest_size                        42
#define AgnssTime_size                           18
#define AgnssUtc_size                            48
#define CellFix_size                             36
#define GpsFix_size                              42
#define MotionEvent_size                         12
#define TRACKER_PB_H_MAX_SIZE                    AgnssEphemeris_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
