/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "tracker.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GpsFix, GpsFix, AUTO)


PB_BIND(TrackSegment, TrackSegment, AUTO)


PB_BIND(CellFix, CellFix, AUTO)


PB_BIND(Entry, Entry, AUTO)


PB_BIND(Obs, Obs, AUTO)



