/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_TRACKER_PB_H_INCLUDED
#define PB_TRACKER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Full GNSS fix. Used as a track segment's anchor (absolute position); a lone
 fix is just a TrackSegment with empty delta arrays. */
typedef struct _GpsFix {
    int32_t lat_e7; /* degrees * 1e7 */
    int32_t lon_e7; /* degrees * 1e7 */
    int32_t alt_dm; /* decimetres */
    uint32_t acc_dm; /* decimetres */
    uint32_t spd_dms; /* dm/s */
    uint32_t hdg_ddeg; /* tenths of a degree */
    uint32_t sats; /* satellites used */
} GpsFix;

/* A run of GNSS positions at a fixed cadence. The anchor is point 0 (absolute);
 dlat[i]/dlon[i]/spd_dms[i] describe point i+1 (i.e. the arrays parallel each
 other and are all the same length = point_count - 1). Deltas are in
 1e-7-degree units, zigzag varint: small (slow / high-rate) deltas cost 1 B,
 typical driving deltas 2 B. Overflow-free by construction: the firmware
 starts a fresh segment (new anchor) before any delta would exceed a tick's
 real range. A stationary run is simply zero deltas (folds in v2's "repeat"
 entry) -- note a zero point costs 2 B on the wire (1 B in dlat + 1 B in dlon),
 not 1.

 spd_dms carries the GNSS-measured (Doppler) speed per point. This is NOT
 derived from the position deltas on the server: at 1 Hz that derivation
 carries ~8 km/h of jitter and at 10 Hz it is unusable (a stationary unit
 would show a phantom ~70 km/h from position noise alone). Doppler speed is
 filtered and costs ~1-2 B/point, so we send it. Being a packed array it may
 be left empty (0 B) in a future low-bandwidth mode; the server then falls
 back to a coarse derived speed. */
typedef struct _TrackSegment {
    bool has_anchor;
    GpsFix anchor;
    uint32_t dt_ms; /* spacing between points */
    pb_callback_t dlat;
    pb_callback_t dlon;
    pb_callback_t spd_dms; /* GNSS Doppler speed, dm/s */
} TrackSegment;

/* Serving-cell observation (no GNSS, or a stationary keepalive). The server
 resolves this to an approximate location. */
typedef struct _CellFix {
    uint32_t mcc;
    uint32_t mnc;
    uint32_t tac;
    uint32_t cell_id; /* 28-bit ECI */
    int32_t rsrp_dbm;
} CellFix;

/* One item in a batch. age_s ages the anchor (track) or the fix (cell). */
typedef struct _Entry {
    uint32_t age_s;
    pb_size_t which_kind;
    union _Entry_kind {
        TrackSegment track;
        CellFix cell;
    } kind;
} Entry;

/* The datagram. version+device_id are shared by every entry in the batch. */
typedef struct _Obs {
    uint32_t version; /* 3 */
    pb_callback_t device_id; /* IMEI on hardware, TRACKER_DEVICE_ID on the sim */
    pb_callback_t entries;
} Obs;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GpsFix_init_default                      {0, 0, 0, 0, 0, 0, 0}
#define TrackSegment_init_default                {false, GpsFix_init_default, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define CellFix_init_default                     {0, 0, 0, 0, 0}
#define Entry_init_default                       {0, 0, {TrackSegment_init_default}}
#define Obs_init_default                         {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define GpsFix_init_zero                         {0, 0, 0, 0, 0, 0, 0}
#define TrackSegment_init_zero                   {false, GpsFix_init_zero, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define CellFix_init_zero                        {0, 0, 0, 0, 0}
#define Entry_init_zero                          {0, 0, {TrackSegment_init_zero}}
#define Obs_init_zero                            {0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GpsFix_lat_e7_tag                        1
#define GpsFix_lon_e7_tag                        2
#define GpsFix_alt_dm_tag                        3
#define GpsFix_acc_dm_tag                        4
#define GpsFix_spd_dms_tag                       5
#define GpsFix_hdg_ddeg_tag                      6
#define GpsFix_sats_tag                          7
#define TrackSegment_anchor_tag                  1
#define TrackSegment_dt_ms_tag                   2
#define TrackSegment_dlat_tag                    3
#define TrackSegment_dlon_tag                    4
#define TrackSegment_spd_dms_tag                 5
#define CellFix_mcc_tag                          1
#define CellFix_mnc_tag                          2
#define CellFix_tac_tag                          3
#define CellFix_cell_id_tag                      4
#define CellFix_rsrp_dbm_tag                     5
#define Entry_age_s_tag                          1
#define Entry_track_tag                          2
#define Entry_cell_tag                           3
#define Obs_version_tag                          1
#define Obs_device_id_tag                        2
#define Obs_entries_tag                          3

/* Struct field encoding specification for nanopb */
#define GpsFix_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   lat_e7,            1) \
X(a, STATIC,   SINGULAR, SINT32,   lon_e7,            2) \
X(a, STATIC,   SINGULAR, SINT32,   alt_dm,            3) \
X(a, STATIC,   SINGULAR, UINT32,   acc_dm,            4) \
X(a, STATIC,   SINGULAR, UINT32,   spd_dms,           5) \
X(a, STATIC,   SINGULAR, UINT32,   hdg_ddeg,          6) \
X(a, STATIC,   SINGULAR, UINT32,   sats,              7)
#define GpsFix_CALLBACK NULL
#define GpsFix_DEFAULT NULL

#define TrackSegment_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  anchor,            1) \
X(a, STATIC,   SINGULAR, UINT32,   dt_ms,             2) \
X(a, CALLBACK, REPEATED, SINT32,   dlat,              3) \
X(a, CALLBACK, REPEATED, SINT32,   dlon,              4) \
X(a, CALLBACK, REPEATED, UINT32,   spd_dms,           5)
#define TrackSegment_CALLBACK pb_default_field_callback
#define TrackSegment_DEFAULT NULL
#define TrackSegment_anchor_MSGTYPE GpsFix

#define CellFix_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mcc,               1) \
X(a, STATIC,   SINGULAR, UINT32,   mnc,               2) \
X(a, STATIC,   SINGULAR, UINT32,   tac,               3) \
X(a, STATIC,   SINGULAR, UINT32,   cell_id,           4) \
X(a, STATIC,   SINGULAR, SINT32,   rsrp_dbm,          5)
#define CellFix_CALLBACK NULL
#define CellFix_DEFAULT NULL

#define Entry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   age_s,             1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,track,kind.track),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,cell,kind.cell),   3)
#define Entry_CALLBACK NULL
#define Entry_DEFAULT NULL
#define Entry_kind_track_MSGTYPE TrackSegment
#define Entry_kind_cell_MSGTYPE CellFix

#define Obs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           3)
#define Obs_CALLBACK pb_default_field_callback
#define Obs_DEFAULT NULL
#define Obs_entries_MSGTYPE Entry

extern const pb_msgdesc_t GpsFix_msg;
extern const pb_msgdesc_t TrackSegment_msg;
extern const pb_msgdesc_t CellFix_msg;
extern const pb_msgdesc_t Entry_msg;
extern const pb_msgdesc_t Obs_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GpsFix_fields &GpsFix_msg
#define TrackSegment_fields &TrackSegment_msg
#define CellFix_fields &CellFix_msg
#define Entry_fields &Entry_msg
#define Obs_fields &Obs_msg

/* Maximum encoded size of messages (where known) */
/* TrackSegment_size depends on runtime parameters */
/* Entry_size depends on runtime parameters */
/* Obs_size depends on runtime parameters */
#define CellFix_size                             30
#define GpsFix_size                              42
#define TRACKER_PB_H_MAX_SIZE                    GpsFix_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
